version: '3.8'

services:
  tests:
    build: .
    container_name: playwright-tests
    volumes:
      - .:/app
    environment:
      - BASE_URL=https://www.saucedemo.com
    command: >
      sh -c "npx playwright test && allure generate ./allure-results --clean -o ./allure-report && allure open ./allure-report"